-- Suppression des tables avec leurs dépendances

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS p_avoirDisponibiliteService CASCADE;
DROP TABLE IF EXISTS p_avoirReserve CASCADE;
DROP TABLE IF EXISTS p_avoirDisponibiliteCoach CASCADE;
DROP TABLE IF EXISTS p_jouer CASCADE;
DROP TABLE IF EXISTS p_Parler CASCADE;
DROP TABLE IF EXISTS p_AnalysesVideo CASCADE;
DROP TABLE IF EXISTS p_Coachings CASCADE;
DROP TABLE IF EXISTS p_Services CASCADE;
DROP TABLE IF EXISTS p_ExemplaireService CASCADE;
DROP TABLE IF EXISTS p_Commandes CASCADE;
DROP TABLE IF EXISTS p_Panier CASCADE;
DROP TABLE IF EXISTS p_Disponibilites CASCADE;
DROP TABLE IF EXISTS p_Classements CASCADE;
DROP TABLE IF EXISTS p_ModesDeJeu CASCADE;
DROP TABLE IF EXISTS p_Utilisateurs CASCADE;
DROP TABLE IF EXISTS p_Coachs CASCADE;
DROP TABLE IF EXISTS p_Langues CASCADE;
DROP TABLE IF EXISTS p_Jeux CASCADE;

DROP TABLE IF EXISTS p_Panier CASCADE;
DROP TABLE IF EXISTS p_avoirMode CASCADE;
DROP TABLE IF EXISTS p_seClasser CASCADE;

DROP TABLE IF EXISTS p_avoirMode CASCADE;
DROP TABLE IF EXISTS p_seClasse CASCADE;
DROP TABLE IF EXISTS p_seClasser CASCADE;
